AWSTemplateFormatVersion: "2010-09-09"
Description: "Root stack for deploying my infrastructure"

Parameters:
  VPCName:
    Type: String
    Default: "default-VPC-Name"

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationtemplate110.s3.ap-south-1.amazonaws.com/templates/vpc.yaml
      Parameters:
        VPCName: !Ref VPCName

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationtemplate110.s3.ap-south-1.amazonaws.com/templates/ecs.yaml
      Parameters:
        VPCName: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetOne: !GetAtt VPCStack.Outputs.PublicSubnet0
        PublicSubnetTwo: !GetAtt VPCStack.Outputs.PublicSubnet1
        DesiredCapacity: "0"
        MaxSize: "1"

Outputs:
  VPCStackOutput:
    Description: "Output from child stack"
    Value: !GetAtt VPCStack.Outputs.VPCId