AWSTemplateFormatVersion: "2010-09-09"
Description: "Root stack for deploying my infrastructure"

Parameters:
  StackName:
    Type: String
    Default: "default-stack-name"

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: /templates/vpc.yaml
      Parameters:
        VPCName: MyParameterizedVPC
        CIDR: 10.5.0.0/16