AWSTemplateFormatVersion: "2010-09-09"
Description: "Root stack for deploying my infrastructure"

Parameters:
  VPCName:
    Type: String
    Default: "default-VPC-Name"

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformationtemplate110.s3.ap-south-1.amazonaws.com/templates/vpc.yaml
      Parameters:
        VPCName: !Ref VPCName