AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for VPC and Subnets creation
Parameters:
  VPCName:
    Type: String
  VPCCIDR:
    Type: String

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VPCName

Outputs:
  VPCId:
    Description: The ID of the created VPC
    Value: !Ref MyVPC